#if !defined(AFX_COLUMNHEADERS_H__57D326BB_4BA4_4103_A42E_30AD71303F42__INCLUDED_)
#define AFX_COLUMNHEADERS_H__57D326BB_4BA4_4103_A42E_30AD71303F42__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CColumnHeader;

/////////////////////////////////////////////////////////////////////////////
// CColumnHeaders wrapper class

class CColumnHeaders : public COleDispatchDriver
{
public:
	CColumnHeaders() {}		// Calls COleDispatchDriver default constructor
	CColumnHeaders(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CColumnHeaders(const CColumnHeaders& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetCount();
	void SetCount(long nNewValue);
	void Clear();
	CColumnHeader GetItem(VARIANT* Index);
	void Remove(VARIANT* Index);
	LPUNKNOWN _NewEnum();
	CColumnHeader Add(VARIANT* Index, VARIANT* Key, VARIANT* Text, VARIANT* Width, VARIANT* Alignment, VARIANT* Icon);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_COLUMNHEADERS_H__57D326BB_4BA4_4103_A42E_30AD71303F42__INCLUDED_)
