#if !defined(AFX_LISTSUBITEM_H__7D0B5E3F_2DAB_40A3_8761_FEA1FF081143__INCLUDED_)
#define AFX_LISTSUBITEM_H__7D0B5E3F_2DAB_40A3_8761_FEA1FF081143__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CListSubItem wrapper class

class CListSubItem : public COleDispatchDriver
{
public:
	CListSubItem() {}		// Calls COleDispatchDriver default constructor
	CListSubItem(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CListSubItem(const CListSubItem& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
	unsigned long GetForeColor();
	void SetForeColor(unsigned long newValue);
	BOOL GetBold();
	void SetBold(BOOL bNewValue);
	VARIANT GetReportIcon();
	void SetReportIcon(const VARIANT& newValue);
	CString GetToolTipText();
	void SetToolTipText(LPCTSTR lpszNewValue);
	long GetIndex();
	void SetIndex(long nNewValue);
	CString GetKey();
	void SetKey(LPCTSTR lpszNewValue);
	VARIANT GetTag();
	void SetTag(const VARIANT& newValue);
	void SetRefTag(const VARIANT& newValue);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LISTSUBITEM_H__7D0B5E3F_2DAB_40A3_8761_FEA1FF081143__INCLUDED_)
