//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ShpEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_SHPEDITOR_FORM              101
#define IDR_MAINFRAME                   128
#define IDR_SHPEDITYPE                  129
#define IDR_EDITOR                      130
#define IDB_BITMAP1                     132
#define IDI_ICON1                       133
#define IDB_BITMAP2                     134
#define IDB_BITMAP3                     135
#define IDB_BITMAP4                     136
#define IDB_BITMAP5                     137
#define IDI_ICON2                       138
#define IDI_ICON3                       139
#define IDI_ICON4                       140
#define IDB_BITMAP6                     141
#define IDB_BITMAP7                     142
#define IDR_MENU_EDITOR                 144
#define IDR_MAP_TOOLS                   145
#define IDD_WELLCOM_DLG                 148
#define IDI_ICON5                       149
#define IDI_ICON6                       150
#define IDI_ICON7                       151
#define IDD_DISTANCE                    152
#define IDD_DIALOG1                     153
#define IDD_COORDINATE                  154
#define IDB_STATUS_BITMAP               155
#define IDB_LAYER_DELETE                156
#define IDB_LAYER_ADD                   157
#define IDR_LAYER_MENU                  158
#define IDI_ICON_GLOBE                  159
#define IDI_ICON_POLYGON                160
#define IDB_VISIBLE                     161
#define IDB_HIDE                        162
#define IDB_BITMAP8                     163
#define IDB_TREEBOOT                    164
#define IDI_TREEBOOT                    165
#define IDC_CROSSCIRCLE                 167
#define IDC_EDITNORMAL                  168
#define IDI_ICON8                       170
#define IDI_SKETCH                      171
#define IDD_DRAW_ARC                    173
#define IDR_MENU_DRAW_ARC               174
#define IDD_SNAPING                     175
#define IDR_MENU_DRAW_POLYGON           176
#define IDI_MOUSE_SELECT                177
#define IDI_GLOBE2                      179
#define IDR_MENU_SKETCH                 180
#define IDB_SKETCH                      181
#define IDR_MENU_MODIFY_FEATURE         183
#define IDR_MENU_SELECT                 184
#define IDD_ADD_FIELDS                  185
#define IDI_PROPERTY                    187
#define IDD_FEATURE_PROPERTY            190
#define IDB_BITMAP9                     192
#define IDD_MERGE_DLG                   194
#define IDD_SELECT_LABEL                195
#define IDR_USER_NORMAL                 232
#define IDR_USER_CROSS                  238
#define IDR_USER_MODIFY                 239
#define IDR_USER_MOVE1                  244
#define IDI_BIG_ARC                     249
#define IDI_SMALL_ARC                   250
#define IDB_BITMAP10                    254
#define IDB_BIG_ARC                     255
#define IDB_SMALL_ARC                   256
#define IDC_MAPCONTROL                  1000
#define IDC_RADIO1                      1001
#define IDC_RADIO2                      1002
#define IDC_DISTANCE                    1003
#define IDC_EDIT_X                      1005
#define IDC_EDIT_Y                      1006
#define IDC_FROM_X                      1008
#define IDC_FROM_Y                      1009
#define IDC_SNAP_POINT                  1009
#define IDC_TO_X                        1010
#define IDC_SNAP_LINE                   1010
#define IDC_TO_Y                        1011
#define IDC_RADIUS                      1012
#define IDC_CLOCKWISE                   1013
#define IDC_CLOCKWISE2                  1014
#define IDC_EDIT_FIELD                  1020
#define IDC_COMBO_FIELD_TYPE            1021
#define IDC_BUTTON_ADD                  1023
#define IDC_LIST_FIELDS                 1024
#define IDC_DLETE                       1027
#define IDC_MODIFY                      1028
#define IDC_GRID                        1029
#define IDC_EXIT                        1030
#define IDC_LISTBOX                     1038
#define IDC_LIST                        1040
#define IDC_SMALL_ARC                   1045
#define IDC_BIG_ARC                     1046
#define ID_EDITOR_MENU                  32771
#define ID_EDITOR_SELECT                32772
#define ID_EDITOR_SKECTH_POLYGON        32773
#define ID_EDITOR_MOVE                  32774
#define ID_EDITOR_CUT                   32775
#define ID_EDITOR_BUFFER                32776
#define ID_EDITOR_CLIP                  32777
#define ID_EDITOR_INTERSECT             32778
#define ID_EDITOR_MERGE                 32779
#define ID_EDITOR_UNION                 32780
#define ID_EDITOR_DIVIDE                32781
#define ID_EDITOR_STOP                  32782
#define ID_EDITOR_STAR                  32783
#define ID_EDITOR_SNAPPING              32784
#define ID_MAP_ZOOMIN                   32785
#define ID_MAP_ZOOMOUT                  32786
#define ID_MAP_PAN                      32787
#define ID_MAP_FULLEXTENT               32788
#define ID_MAP_ARROW                    32789
#define ID_MAP_SELECT                   32790
#define ID_EDITOR_COPY                  32791
#define ID_EDITOR_PASTE                 32792
#define ID_EDITOR_DELETE                32793
#define ID_EDITOR_UNDO                  32794
#define ID_EDITOR_REDO                  32795
#define ID_ADD_REFERENCE                32797
#define ID_EDITOR_VISIBLE               32799
#define ID_FILE_ADDSHP                  32800
#define ID_DELETE_REFERENCE             32801
#define ID_LAYER_COLOR                  32801
#define ID_FILE_NEWSHP                  32802
#define ID_FILE_SAVESHP                 32803
#define ID_FILE_SAVESHP_AS              32804
#define ID_TOOLS_VISIBLE                32805
#define ID_EDITOR_SKETCH_LINE           32806
#define ID_EDITOR_CUT_FEATURE           32807
#define ID_FILE_DELLAYER                32808
#define ID_LAYER_MANAGE                 32809
#define ID_FILE_ADDREF                  32810
#define ID_LAYER_SYMBOL                 32812
#define ID_EDITOR_SKETCH_CIRCLE         32821
#define ID_EDITOR_SKETCH_ARC            32823
#define ID_EDITOR_SKETCH_ARC2           32824
#define ID_DRAW_COORDINATE              32825
#define ID_DRAW_OFFSET                  32826
#define ID_DRAW_FINISH                  32827
#define ID_DRAW_CONCEL_MENU             32828
#define ID_DRAW_DELETE_SKETCH           32829
#define ID_DRAW_RADIUS                  32830
#define ID_BUTTON32832                  32832
#define ID_EDITOR_SKECTH                32833
#define ID_EDITOR_MODIFY_INSERT_VERTEX  32835
#define ID_EDITOR_MODIFY_BACK           32836
#define ID_EDITOR_MODIFY_DELETE_VERTEX  32837
#define ID_EDITOR_MODIFY_CANCEL         32838
#define ID_EDITOR_PROPERTY              32839
#define ID_LAYER_PROPERTY               32841
#define ID_EDITOR_EXCHANGE_INDEX        32843
#define ID_EDITOR_EXCHANGE_LAYER_INDEX  32844
#define ID_LAYER_SHOW_LABEL             32845

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        257
#define _APS_NEXT_COMMAND_VALUE         32848
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
